

---



# Section A - Theory


---



## Q1.Ans:

Following is the difference between **'is' operator** and **'==' operator**


*   **'is' operator** is a operator used for comparing references.
*   **'==' operator** is a operator used for comparing values.

For example, let two variable **'a'** and **'b'** point to address **a005f** and **a00f5** respectively and both store integer list i.e, **[1, 5, 7,]**.

*   a is b --> False
*   a == b --> True

In [46]:
a = [1, 5, 7,]
b = [1, 5, 7,]
print(a is b)
print(a == b)

False
True


## Q2.Ans:
*   Mutable : List, Set, Dict,
*   Immutable : String, Tuple, Int, Float, Bool

Immutability ensures data cannot be accidentally modified, which make safe to use anywhere where data integrity matters.



## Q3.Ans:

 My code prediction : True but Actual answer is False. The reason behind this is that in binary representation 0.1 ans 0.2 can be exactly represented, so there some has a tiny rounding error which is different form actual 0.3 value.

In [47]:
print(0.1 + 0.2 == 0.3)

False


## Q4.Ans:

 Following are the three reasons where i would like to use tuples instead od list.


1.  To store Customer record like (name, phone, email) in tuple to avoide accidentally modifying , maintain data integrity.
2.   As keys for dictoary or constructing dictonary becouse tuples as key wrks but list as key throws errors.
3.  And while returing values from a funtion so that the caller dosen't modify any value.



## Q5.Ans:
1. **Without hash:** Becouse dictonay create and store data in key value pair and to find the value or the data we only need to give key.

2. **With hash:** It's basicaly creats a hashmap and for each given value and each hashvalue is a unique hashvalue which refers to only and only to that perticular value or data so its easy to accesse them

## Q6.Ans:


**range()**



1.   basic standar libary function
2.   return object
3.   can't do vectorized operations also can't do float step give error

**numpy.arange()**

1.   specificly build for numpy libery
2.   return a numpy array
3.   we can do vectorized operations, and we can also do float step





## Q7.Ans:


 **list.append(x)**: it append the new alement at the end of the list, length increse by one element


 **list.extend(x)**: it can append list of elements at the of the list at once.length increse by lenght of the list that has being appenderd.


 **list.insert(i,x)**: it insert the the element into the specific index in the list and push rest of element one step back, length increse by one element

examples are given blow:

In [48]:
# For append()
x = [6,7]
list_ = [1,2,3,4,5]
list_.append(x)
print(list_)
print(len(list_))


# For extend()
x = [6,7]
list_ = [1,2,3,4,5]
list_.extend(x)
print(list_)
print(len(list_))


# For insert()
x = [6,7]
list_ = [1,2,3,4,5]
list_.insert(2,x)
print(list_)
print(len(list_))

[1, 2, 3, 4, 5, [6, 7]]
6
[1, 2, 3, 4, 5, 6, 7]
7
[1, 2, [6, 7], 3, 4, 5]
6


## Q8.Ans:

 **'*'** is used **Unpaking** in python

1.   a, *b, c = [10, 20, 30, 40, 50] : in the a = 10, c = 50 and b = [20,30,40]
2.   a, *b, c = [10, 20]: in this a =10, c = 20, and b = []

3.  a, *b, c = [10] : throws ValueError , becouse a =50, b,c  nothing left in list to give them.





## Q9.Ans:






In [49]:
# / is divide oprator do normal division.
# returns float
print(-7/2) # ans: -3.5


# // is floor division give integer value of a division or highest integar value.
# returns int
print(-7//2) # ans: -4


# % is modulus operator it's give the reminder of a division.
# returns int
print(-7%2) # ans: 1


# ** is exponent or power operation use to calculate power of and integer
# return float or int depending appon values given
print(-7**2) # ans: -49

-3.5
-4
1
-49


## Q10.Ans:

Numpy is faster becouse :


1.   elements are in contiguous memory.
2.   numpy have fixed datatype so not type checking is required unlike list can have different type of datatype.
3.   we can do vectorized operation in numpy array with out using any loops.






---



# Section B - Output Prediction


---



## Q11.Ans:

my output:

    matrix1 = [[99, 0, 0], [0, 0, 0], [0, 0, 0]]

    matrix2 = [[99, 0, 0], [99, 0, 0], [99, 0, 0]]

the second line behave differetly becouse while creating the second matrix all three rows were pointing to the same object and changing one will modfiy the other matrix rows too.

In [50]:
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3
matrix1[0][0] = 99
matrix2[0][0] = 99
print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


## Q12.Ans:

my output:

x = [1, 2, 3, 4]

y = [1, 2, 3]

a = [1, 2, 3, 4]

b = [1, 2, 3, 4]


in this code **x** is poiting to object [1,2,3], and **y** is point to **x** , when we did** x = x + [4] **, a new object get greated and now **x** refers to that new object i.e, [1,2,3,4]. and **y** still pointing to the old object so it dosent get change.

In case of **a** and **b** , both are refering to same object but here we did in place modification matlab updated the same object i.e, **x += [4]** there **a** and **b** are still pointing to the updated object and both shows changes.



In [51]:
x = [1, 2, 3]
y = x
x = x + [4]
print("x =", x)
print("y =", y)
a = [1, 2, 3]
b = a
a += [4]
print("a =", a)
print("b =", b)


x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


## Q13.Ans:

value of **i** : well be 4 , becouse range() goes from 0 to 5-1, i.e, 4 so after for loop complete the value of **i** well become 4.

and

in case of **j** : the range function works 0 to n-1, unless starting point is defined in this case range is going from 0 to 0-1 in this case for loop will not run and j will never be created which will give error.


In [52]:
# NOTE:- remove comments for the following:
# for i in range(5):
#  pass
# print(i)
# for j in range(0):
#  pass
# print(j)

## Q14.Ans:






print("10" + "20") : give concatenated string --> "1020".

print(10 + 20) : give sum of 10 and 20 --> 30 (integer value).

print("10" * 3) : give triple of the steing --> "101010".

print(10 * "3") : give 10 times of string --> "3333333333".

print("10" + 20) : give error different datatype summation.

print(int("10") + 20) : give int 30 as sum of 10 and 20 , becouse "10" is typecaste into integer value.

In [53]:
# NOTE:- remove comments for the following:
# print("10" + "20")
# print(10 + 20)
# print("10" * 3)
# print(10 * "3")
# print("10" + 20)
# print(int("10") + 20)

## Q15.Ans:

print(0 or 5) : True i.e, 5

print(5 or 0) : True i.e, 5

print(None or "hello") : True i.e, "hello"

print(0 and 5) : False i.e, 0

print(5 and 10) : True but max value i.e, 10

print([] or "default") : True i.e, "default"

print([0] or "default") : True i.e, [0] the fist ture encounter


in python or return trur when it incounter first true, and return false as soon as it gits ita first false value, no furthere experation required.


In [54]:
# NOTE:- remove comments for the following:
# print(0 or 5)
# print(5 or 0)
# print(None or "hello")
# print(0 and 5)
# print(5 and 10)
# print([] or "default")
# print([0] or "default")

# Section - C  : Coding Practice



## C1 – Warm-up (Q16-Q20)


### Q16.Ans:



In [55]:
#   (a) using arithmetic
a = 10
b = 20
a = a+b
b = a-b
a = a-b
print(a,b)

#   (b) using XOR (`^`)
a = 10
b = 20
a = a^b
b = a^b
a = a^b
print(a,b)

#   (c) using tuple unpacking
a = 10
b = 20
a,b = b,a
print(a,b)

"""Most Pythonic is tuple unpaking."""

20 10
20 10
20 10


'Most Pythonic is tuple unpaking.'

### Q17.Ans:



In [56]:

print("="*30)
price = float(input("  Enter the price: "))
quantity = int(input("  Enter the quantity: "))
print("="*30)
subtotal = price * quantity
gst_18 = round(subtotal * 0.18, 2)
total_cost = subtotal + gst_18
delivery_cost = 40.00

if total_cost <= 499:
    total_cost += delivery_cost
else :
  delivery_cost = 0.00
  total_cost += delivery_cost


print()
print(" Subtotal:      ₹", subtotal)
print(" GST (18%):     ₹", gst_18)
print(" Delivery Cost: ₹", delivery_cost)
print("-"*30)
print(" Total cost:    ₹", round(total_cost, 2))
print("="*30)

  Enter the price: 45
  Enter the quantity: 9

 Subtotal:      ₹ 405.0
 GST (18%):     ₹ 72.9
 Delivery Cost: ₹ 40.0
------------------------------
 Total cost:    ₹ 517.9


### Q18.Ans:



In [57]:
print("="*40)
temp = float(input(" Enter temperature: "))
unit = input(" Enter temperature unit (C or F): ")
print("="*40)

if unit.lower() == 'c':
    result = round((temp * 9/5) + 32, 2)
    print(f" Temprature : {result} F")
elif unit.lower() == 'f':
    result = round((temp - 32) * 5/9, 2)
    print(f" Temprature : {result} C")
else:
    print(f" 55Error: Invalid unit '{unit}'.\n8 Please enter C or F only.")
print("="*40)

 Enter temperature: 90
 Enter temperature unit (C or F): f
 Temprature : 32.22 C


### Q19.Ans:



In [58]:
number = int(input("Enter Four-Digit number only: "))

if number < 1000 or number > 9999:
    print(f"Error: {number} is not a 4-digit number!")
else:
    temp = number
    total = 0

    while temp > 0:
        last_digit = temp % 10
        total += last_digit
        temp //= 10

    print(f"Sum of digits of {number}: {total}")

Enter Four-Digit number only: 8521
Sum of digits of 8521: 16


### Q20.Ans:



In [59]:
user_input = input("Enter input")

try:
  is_int = int(user_input)
  print(f"{user_input} is an integer.")
except:
  try:
    is_float = float(user_input)
    print(f"{user_input} is a float.")
  except:
    print(f"{user_input} is a string.")

Enter input4568
4568 is an integer.


## C2 – Conditionals & Logic (Q21-Q25)



### Q21.Ans:



In [60]:
annual_income = float(input("Enter your annual income: "))

slab1_tax = 0
slab2_tax = 0
slab3_tax = 0
slab4_tax = 0
slab5_tax = 0
slab6_tax = 0

# Slab 1: 0 - 3,00,000 → 0%
# no tax

# Slab 2: 3,00,001 - 7,00,000 → 5%
if annual_income > 300000:
    slab2_tax = (min(annual_income, 700000) - 300000) * 0.05

# Slab 3: 7,00,001 - 10,00,000 → 10%
if annual_income > 700000:
    slab3_tax = (min(annual_income, 1000000) - 700000) * 0.10

# Slab 4: 10,00,001 - 12,00,000 → 15%
if annual_income > 1000000:
    slab4_tax = (min(annual_income, 1200000) - 1000000) * 0.15

# Slab 5: 12,00,001 - 15,00,000 → 20%
if annual_income > 1200000:
    slab5_tax = (min(annual_income, 1500000) - 1200000) * 0.20

# Slab 6: 15,00,001+ → 30%
if annual_income > 1500000:
    slab6_tax = (annual_income - 1500000) * 0.30

total_tax = slab1_tax + slab2_tax + slab3_tax + slab4_tax + slab5_tax + slab6_tax

print(f"Slab 1 tax (0-3L)     : ₹{slab1_tax}")
print(f"Slab 2 tax (3L-7L)    : ₹{slab2_tax}")
print(f"Slab 3 tax (7L-10L)   : ₹{slab3_tax}")
print(f"Slab 4 tax (10L-12L)  : ₹{slab4_tax}")
print(f"Slab 5 tax (12L-15L)  : ₹{slab5_tax}")
print(f"Slab 6 tax (15L+)     : ₹{slab6_tax}")
print(f"Total tax payable     : ₹{total_tax}")

Enter your annual income: 785612
Slab 1 tax (0-3L)     : ₹0
Slab 2 tax (3L-7L)    : ₹20000.0
Slab 3 tax (7L-10L)   : ₹8561.2
Slab 4 tax (10L-12L)  : ₹0
Slab 5 tax (12L-15L)  : ₹0
Slab 6 tax (15L+)     : ₹0
Total tax payable     : ₹28561.2


### Q22.Ans:



In [61]:
pan_no = input("Enter your PAN no.: ").upper()

valid = True

if len(pan_no) != 10:
    valid = False
    reason  = "Invalid length of pan no.."
elif not pan_no[:5].isalpha():
    valid = False
    reason  = "First 5 characters must be uppercase letters."
elif not pan_no[5:9].isdigit():
    valid = False
    reason  = "Characters 6-9 must be digits."
elif not pan_no[-1].isalpha():
    valid = False
    reason  = "Last character must be an uppercase letter."

if valid:
    print("Valid PAN ")
else:
    print("Invalid PAN ")
    print(reason)


Enter your PAN no.: AAset6789o
Valid PAN 


### Q23.Ans:

In [62]:
units = int(input("Enter the units consumed: "))
fix_charge = 110.00

charge1 = 0
charge2 = 0
charge3 = 0
charge4 = 0

# Slab 1: 0-50 units → 4.10
charge1 = round(min(units, 50) * 4.10,2)

# Slab 2: 51-100 units → 5.55
if units > 50:
    charge2 = round((min(units, 100) - 50) * 5.55,2)

# Slab 3: 101-200 units → 7.10
if units > 100:
    charge3 = round((min(units, 200) - 100) * 7.10,2)

# Slab 4: 200+ units → 8.15
if units > 200:
    charge4 = round((units - 200) * 8.15,2)

charges = [charge1,charge2,charge3,charge4]

energy_charge = charge1 + charge2 + charge3 + charge4
units_charges = [
    (charge1, "0-50"),
    (charge2, "50-100"),
    (charge3, "100-200"),
    (charge4, "200-above")
]

gov_tax = round((energy_charge + fix_charge) * 0.06, 2)
total = round(energy_charge + fix_charge + gov_tax, 2)

print('-'*45)
print(f" Units consumed : {units}")
print(f" Charges:")
for charge, slab in units_charges:
    if charge != 0:
        print(f" For units {slab}: ₹{charge}")
print('-'*45)
print(f" Energy charge (sub-total)  : ₹{energy_charge}")
print(f" Fixed charge   :   ₹{fix_charge}")
print(f" Govt tax (6%)  :   ₹{gov_tax}")
print('-'*45)
print(f" Total bill     :   ₹{total}")

Enter the units consumed: 300
---------------------------------------------
 Units consumed : 300
 Charges:
 For units 0-50: ₹205.0
 For units 50-100: ₹277.5
 For units 100-200: ₹710.0
 For units 200-above: ₹815.0
---------------------------------------------
 Energy charge (sub-total)  : ₹2007.5
 Fixed charge   :   ₹110.0
 Govt tax (6%)  :   ₹127.05
---------------------------------------------
 Total bill     :   ₹2244.55


### Q24.Ans:

In [63]:
balls = int(input("Enter the no. of balls played: "))

# checking the 0 ball case
if balls == 0:
  print("Error: No balls played.")
else:
  # if ball is not zero then takes runs and caluculate strike_rate SR
  runs = int(input("Enter the runs scored: "))
  SR = round((runs / balls) * 100, 2)

  if SR > 150 :
    print("Explosive (T20 finisher)")
  elif SR > 100 :
    print("Agressive (Top order T20)")
  elif SR > 75 :
    print("Steady (ODI Anchor)")
  else:
    print("Defensive (Test match)")



Enter the no. of balls played: 80
Enter the runs scored: 120
Agressive (Top order T20)


### Q25.Ans:

In [64]:
w = float(input("Enter the weight (in kg): "))
h = float(input("Enter the height (in cm): "))

#changing height cm to m
h = round( h/100, 2)

BMI = round(w / (h**2), 2)

if BMI < 18.5:
    category = "Underweight"
elif BMI <= 22.9:
    category = "Normal"
elif BMI <= 24.9:
    category = "Overweight"
elif BMI <= 29.9:
    category = "Obese Class I"
else:
    category = "Obese Class II"

print(f"BMI: {BMI}\nCategory: {category}")


Enter the weight (in kg): 89
Enter the height (in cm): 150
BMI: 39.56
Category: Obese Class II


## C3 – Nested Loop Patterns (Q26-Q30)

### Q26.Ans:


In [65]:
n = 5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


### Q27.Ans:

In [66]:
n = 5
for i in range(1,n+1):
  print(" "*(n-i),end="")
  for j in range(1,i+1):
    print(j,end=" ")
  for k in range(i-1,0,-1):
    print(k,end=" ")
  print()

for i in range(n-1,0,-1):
  print(" "*(n-i),end="")
  for j in range(1,i+1):
    print(j,end=" ")
  for k in range(i-1,0,-1):
    print(k,end=" ")
  print()


    1 
   1 2 1 
  1 2 3 2 1 
 1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
 1 2 3 4 3 2 1 
  1 2 3 2 1 
   1 2 1 
    1 


### Q28.Ans:

In [67]:
n = int(input("Enter number: "))
for i in range(1,n+1):
  if i == 1 or i == n:
    print("* "*n)
  else:
    print("*"," "*(n*2 -5),"*") # in actual the in between space should be 2*n-3, but when i use ',' in print() it add 1 space for each ',' so space become 2*n-3-2


Enter number: 7
* * * * * * * 
*           *
*           *
*           *
*           *
*           *
* * * * * * * 


### Q29.Ans:

In [68]:
n = 5
row = [1]

for i in range(n):

    print(" " * (n-i), end="")
    print(*row)


    new_row = [1]
    for j in range(len(row)-1):
        new_row.append(row[j] + row[j+1])
    new_row.append(1)

    row = new_row

     1
    1 1
   1 2 1
  1 3 3 1
 1 4 6 4 1


### Q30.Ans:

In [69]:
n = int(input("Enter number: "))
for i in range(1, n+1):
    for j in range(1, i+1):
        print(chr(65 + j-1), end=" ")
    print()

Enter number: 9
A 
A B 
A B C 
A B C D 
A B C D E 
A B C D E F 
A B C D E F G 
A B C D E F G H 
A B C D E F G H I 


## C4 – Loop Logic (Q31-Q36)

### Q31.Ans:


In [70]:
result = []
for num in range(1, 10000):
    digits = len(str(num))
    total = 0
    temp = num
    while temp > 0:
        total += (temp % 10) ** digits
        temp //= 10
    if total == num:
        result.append(num)
print(", ".join(map(str, result)))
print(f"Count: {len(result)}")

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


### Q32.Ans:


In [71]:
n = int(input("Enter N: "))
a, b = 0, 1
total = 0
for i in range(n):
    print(a, end=" ")
    total += a
    a, b = b, a+b
print(f"\nSum: {total}")

Enter N: 11
0 1 1 2 3 5 8 13 21 34 55 
Sum: 143


### Q33.Ans:


In [72]:
n = int(input("Enter N: "))

def is_prime(num):
    if num < 2:
        return False
    i = 2
    while i * i <= num:  # sqrt tak — no library!
        if num % i == 0:
            return False
        i += 1
    return True

# check if n itself is prime
print(f"{n} is {'Prime' if is_prime(n) else 'Not Prime'}")

# sum of all primes from 2 to n
prime_sum = 0
for num in range(2, n+1):
    if is_prime(num):
        prime_sum += num

print(f"Sum of all primes from 2 to {n}: {prime_sum}")

Enter N: 11
11 is Prime
Sum of all primes from 2 to 11: 28


### Q34.Ans:


In [73]:
n = int(input("Enter number: "))
if n < 0:
    print("Not palindrome")
else:
    temp = n
    rev = 0
    while temp > 0:
        rev = rev * 10 + temp % 10
        temp //= 10
    print("Palindrome" if n == rev else "Not palindrome")

Enter number: 151
Palindrome


### Q35.Ans:


In [74]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
x, y = a, b
while y:
    x, y = y, x % y
hcf = x
lcm = (a * b) // hcf
print(f"HCF: {hcf}, LCM: {lcm}")

Enter first number: 8
Enter second number: 6
HCF: 2, LCM: 24


### Q36.Ans:

In [75]:
sentence = input("Enter sentence: ")
words = len(sentence.split())
chars = vowels = consonants = digits = spaces = special = 0
for ch in sentence:
    chars += 1
    if ch in "aeiouAEIOU":
        vowels += 1
    elif ch.isalpha():
        consonants += 1
    elif ch.isdigit():
        digits += 1
    elif ch == " ":
        spaces += 1
    else:
        special += 1
ans = f"""Chars:{chars},
Words:{words},
Vowels:{vowels},
Consonants:{consonants},
Digits:{digits},
Spaces:{spaces},
Special:{special}"""
print(ans)

Enter sentence: shoyal the . drgdhg 90 ::
Chars:25, 
Words:6, 
Vowels:3, 
Consonants:12, 
Digits:2, 
Spaces:5, 
Special:3


## C5 – Lists, Tuples, Sets, Dicts (Q37-Q42)

### Q37.Ans:


In [90]:
while True:
    marks = list(map(int, input("Enter exactly 10 marks: ").split()))
    if len(marks) == 10:
        break
    print(f"Error: You entered {len(marks)} marks. Please enter exactly 10!")

max_m = marks[0]
min_m = marks[0]
total = 0
for m in marks:
    if m > max_m: max_m = m
    if m < min_m: min_m = m
    total += m
avg = total / len(marks)
above_avg = sum(1 for m in marks if m > avg)

# second highest
unique = list(set(marks))
unique_sorted_max = unique[0]
second = unique[0]
for u in unique:
    if u > unique_sorted_max:
        second = unique_sorted_max
        unique_sorted_max = u
    elif u > second and u != unique_sorted_max:
        second = u

print(f"""
Max        : {max_m}
Min        : {min_m}
Average    : {avg:.2f}
Above avg  : {above_avg}
2nd highest: {second}""")

Enter exactly 10 marks: 45 45 85 74 95 68 52 51 54 54

Max        : 95
Min        : 45
Average    : 62.30
Above avg  : 4
2nd highest: 85


### Q38.Ans:


In [77]:
sentence = input("Enter review: ").lower()
words = sentence.split()
freq = {}
for word in words:
    freq[word] = freq.get(word, 0) + 1

# sort by frequency
sorted_words = sorted(freq, key=lambda x: freq[x], reverse=True)
for word in sorted_words:
    print(f"{word}: {freq[word]}")
print(f"Most frequent: {sorted_words[0]} ({freq[sorted_words[0]]})")

Enter review: t trhsb gs zvf gd gs s gs gs gs fhfa tsv
gs: 5
t: 1
trhsb: 1
zvf: 1
gd: 1
s: 1
fhfa: 1
tsv: 1
Most frequent: gs (5)


### Q39.Ans:


In [78]:
states = {"Karnataka":"Bengaluru", "Maharashtra":"Mumbai",
          "Delhi":"New Delhi", "Rajasthan":"Jaipur", "Kerala":"Thiruvananthapuram"}

while True:
    print("\n1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit")
    choice = input("Choice: ")

    match choice:
        case "1":
            s = input("State: ").title()    # "new delhi" → "New Delhi"
            c = input("Capital: ").title()
            states[s] = c
            print(f"Added: {s} → {c}")
        case "2":
            s = input("State: ").title()
            if s in states:
                c = input("New capital: ").title()
                states[s] = c
                print(f"Updated: {s} → {c}")
            else:
                print(f"Not found: {s}")
        case "3":
            s = input("State: ").title()
            if s in states:
                del states[s]
                print(f"Deleted: {s}")
            else:
                print(f"Not found: {s}")
        case "4":
            s = input("State: ").title()
            print(f"Capital: {states.get(s, 'Not found')}")
        case "5":
            print("\n--- All States ---")
            for s in sorted(states):
                print(f"{s}: {states[s]}")
        case "6":
            print("Goodbye!")
            break
        case _:
            print("Invalid choice! Enter 1-6 only.")


1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 5

--- All States ---
Delhi: New Delhi
Karnataka: Bengaluru
Kerala: Thiruvananthapuram
Maharashtra: Mumbai
Rajasthan: Jaipur

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 4
State: delhi
Capital: New Delhi

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 1
State: west bangal
Capital: kolkata
Added: West Bangal → Kolkata

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 4
State: west bangal
Capital: Kolkata

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 5

--- All States ---
Delhi: New Delhi
Karnataka: Bengaluru
Kerala: Thiruvananthapuram
Maharashtra: Mumbai
Rajasthan: Jaipur
West Bangal: Kolkata

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit
Choice: 6
Goodbye!


### Q40.Ans:


In [79]:
a = {"Python", "Java", "C++", "SQL"}
b = {"Java", "JavaScript", "Python", "Go", "SQL"}
print(f"Both sections: {a & b}")
print(f"Only A: {a - b}")
print(f"Only B: {b - a}")
print(f"All unique: {a | b}")
print(f"Exclusive: {a ^ b}")

Both sections: {'Java', 'SQL', 'Python'}
Only A: {'C++'}
Only B: {'Go', 'JavaScript'}
All unique: {'C++', 'Java', 'SQL', 'Python', 'JavaScript', 'Go'}
Exclusive: {'C++', 'JavaScript', 'Go'}


### Q41.Ans:


In [80]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

# here max(prices) will give the max value
# then i used that max value and find its index i, becouse the ith day in the days list will be the max value day so the {days[prices.index(max(prices))]} will retrun the day
print(f"Max: {max(prices)} on {days[prices.index(max(prices))]}")
print(f"Min: {min(prices)} on {days[prices.index(min(prices))]}")
print(f"Average: {sum(prices)/len(prices):.2f}")

max_gain = 0
gain_days = ""
for i in range(1, len(prices)):
    gain = prices[i] - prices[i-1]
    if gain > max_gain:
        max_gain = gain
        gain_days = f"{days[i-1]} to {days[i]}"
print(f"Biggest gain: ₹{max_gain} ({gain_days})")

volatility = sum(abs(prices[i]-prices[i-1]) for i in range(1,len(prices)))
print(f"Volatility: ₹{volatility}")

Max: 4055 on Sun
Min: 3845 on Mon
Average: 3949.29
Biggest gain: ₹77 (Wed to Thu)
Volatility: ₹286


### Q42.Ans:


In [81]:
nums = [1,2,3,2,4,5,1,6,7,8,9,3,10,11,12,4,13,14,15,5]
freq = {}
for n in nums:
    freq[n] = freq.get(n, 0) + 1
print(f"Unique: {set(nums)}")
print(f"More than once: {[k for k in freq if freq[k] > 1]}")
print(f"Exactly once: {[k for k in freq if freq[k] == 1]}")

Unique: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
More than once: [1, 2, 3, 4, 5]
Exactly once: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


## C6 – Strings (Q43-Q45)


### Q43.Ans:


In [82]:
sentence = input("Enter sentence: ")
cleaned = ""
for ch in sentence.lower():
    if ch.isalnum():
        cleaned += ch
print("Palindrome" if cleaned == cleaned[::-1] else "Not palindrome")

Enter sentence: aaSafha dsfasj egt
Not palindrome


### Q44.Ans:


In [83]:
sentence = input("Enter sentence: ")
words = sentence.split()
result = ""
for word in words:
    result += word[0].upper() + word[1:].lower() + " "
print(result.strip())

Enter sentence: dfah safhre sffskr
Dfah Safhre Sffskr


### Q45.Ans:


In [84]:
msg = input("Enter message: ")
shift = int(input("Enter shift: "))
result = ""
for ch in msg:
    if ch.isalpha():
        base = ord('A') if ch.isupper() else ord('a')  # this here tell us the char is lower or upper
        result += chr((ord(ch) - base + shift) % 26 + base) # this he i shift the letter under limit from A to Z ans a to z
    else:
        result += ch
print(result)

Enter message: euhre sd tsa
Enter shift: 2
gwjtg uf vuc


## C7 – Functions (Q46-Q47)

### Q46.Ans:


In [85]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        base = round(amount / (1 + gst_rate/100), 2)
        gst = round(amount - base, 2)
    else:
        base = round(amount, 2)
        gst = round(amount * gst_rate/100, 2)
    total = round(base + gst, 2)
    return (base, gst, total)

print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180.0)
(500, 25.0, 525.0)


### Q47.Ans:


In [86]:
def power(base, exp):
    if exp == 0:
        return 1
    if exp < 0:
        return round(1 / power(base, -exp),4)
    return round(base * power(base, exp-1),4)

print(power(2,10))
print(power(5,0))
print(power(3,-2))

1024
1
0.1111


## C8 – NumPy Foundations (Q48-Q50)

### Q48.Ans:


In [87]:
import numpy as np
identity_mat = np.eye(5)
print("Identity Matrix: ")
print(identity_mat)
print()

mat = identity_mat * 10

print("After Multipication with 10 the matrix become: ")
print(mat)
print()

print("After Transpose: ")
print(mat.T)  # transpose = same ,becouse mat has same digonal elements
print()

print("Sum of all the digonal elements: ",np.trace(mat))   # diagonal sum
print("Sum of all the elements in the matrix: ",np.sum(mat))     # all elements sum

Identity Matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After Multipication with 10 the matrix become: 
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

After Transpose: 
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of all the digonal elements:  50.0
Sum of all the elements in the matrix:  50.0


### Q49.Ans:


In [88]:
import numpy as np
sales = np.array([12000,18500,14200,22100,19800,35200,28400])
days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
print(f"Total: ₹{np.sum(sales)}")
print(f"Average: ₹{np.mean(sales):.2f}")
print(f"Max day: {days[np.argmax(sales)]}")
print(f"Above average days: {np.sum(sales > np.mean(sales))}")
print(f"Growth Mon-Sun: {((sales[-1]-sales[0])/sales[0])*100:.2f}%")
changes = np.diff(sales) / sales[:-1] * 100
print(f"Day-on-day changes: {np.round(changes, 2)}")

Total: ₹150200
Average: ₹21457.14
Max day: Sat
Above average days: 3
Growth Mon-Sun: 136.67%
Day-on-day changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


### Q50.Ans:

In [89]:
import numpy as np
mat = np.zeros((5,5), dtype=int)
mat[0, :] = 1    # this make all the 1st row elements 1
mat[-1, :] = 1   # this make all the last roe elements 1
mat[:, 0] = 1    # and this one make all coloum 1 element 1
mat[:, -1] = 1   # and this do the same but to the al element at the last coloum
print(mat)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
